import { ImageResponse } from 'next/og';
import { getDictionary, isLocale, pickLang, FALLBACK_LOCALE } from '@/lib/i18n';
import { getArticleBySlug } from '@/lib/data/content';
import { clusterOfArticle } from '@/lib/clusters';
import { OgCard } from '@/lib/og';

/**
 * /{locale}/blog/{slug}/hero — the article's typographic hero card (1600×900)
 * for posts that have no gallery cover: the title in the page's language, the
 * cluster label as the badge and the Bab Makka mark. Generated by next/og
 * (Satori) on the Vercel function, cached a day, no external service, no
 * cost — the free pipeline the brief asks for. The 1200×630 share card is the
 * sibling opengraph-image route.
 */
export const revalidate = 86400;
const SIZE = { width: 1600, height: 900 };

export async function GET(_request, { params }) {
  const { locale, slug } = await params;
  const loc = isLocale(locale) ? locale : FALLBACK_LOCALE;
  const t = getDictionary(loc);
  const article = await getArticleBySlug(slug);
  if (!article) return new Response('Not found', { status: 404 });
  const cluster = clusterOfArticle(article);
  const badge = cluster ? t.clusters.names[cluster.id] : t.articleCategory?.[article.category] ?? article.category;
  return new ImageResponse(
    <OgCard title={pickLang(article, 'title', loc) ?? article.slug} badge={badge} meta={null} scale={SIZE.width / 1200} />,
    { ...SIZE, headers: { 'cache-control': 'public, s-maxage=86400, stale-while-revalidate=604800' } },
  );
}
